"""
Unit tests for file upload security functions.

Tests for:
- Filename sanitization (path traversal protection)
- MIME type validation
"""

from __future__ import annotations

import sys
from pathlib import Path

_project_root = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(_project_root))

import pytest

from backend.services.file_processor import _sanitize_filename, validate_mime_type
import tempfile
import os


class TestFilenameSanitization:
    """Tests for _sanitize_filename function."""

    def test_forward_slash_traversal(self):
        """Test that ../ is stripped."""
        safe_name, _ = _sanitize_filename("../../../etc/passwd")
        assert "/" not in safe_name
        assert ".." not in safe_name

    def test_backslash_traversal(self):
        """Test that backslash traversal is stripped."""
        safe_name, _ = _sanitize_filename("..\\..\\..\\windows\\system32\\config\\sam")
        assert "\\" not in safe_name
        assert ".." not in safe_name

    def test_null_bytes_removed(self):
        """Test that null bytes are removed."""
        safe_name, _ = _sanitize_filename("test.txt\x00../../etc/passwd")
        assert "\x00" not in safe_name

    def test_absolute_path_rejected(self):
        """Test that absolute paths are sanitized."""
        safe_name, _ = _sanitize_filename("/etc/passwd")
        assert not safe_name.startswith("/")

    def test_empty_filename_returns_uuid(self):
        """Test empty filename returns UUID (secure default)."""
        safe_name, ext = _sanitize_filename("")
        assert safe_name.endswith(".txt")
        assert len(safe_name) == 36  # 32 hex + ".txt" = 36 chars
        assert ext == ".txt"

    def test_none_filename_returns_uuid(self):
        """Test None filename returns UUID (secure default)."""
        safe_name, ext = _sanitize_filename(None)  # type: ignore
        assert safe_name.endswith(".txt")
        assert len(safe_name) == 36
        assert ext == ".txt"

    def test_special_characters_removed(self):
        """Test dangerous special characters are removed."""
        dangerous = "test<>:\"/\\|?*.txt"
        safe_name, _ = _sanitize_filename(dangerous)
        dangerous_chars = ['<', '>', ':', '"', '/', '\\', '|', '?', '*']
        for char in dangerous_chars:
            assert char not in safe_name

    def test_double_dot_sequences(self):
        """Test multiple .../ sequences are handled."""
        safe_name, _ = _sanitize_filename("....//....//test.txt")
        assert ".." not in safe_name

    def test_extension_preserved(self):
        """Test that valid extensions are preserved."""
        safe_name, ext = _sanitize_filename("document.pdf")
        assert ext == ".pdf"
        assert safe_name.endswith(".pdf")

    def test_unsupported_extension_defaults_to_txt(self):
        """Test unsupported extensions default to .txt."""
        safe_name, ext = _sanitize_filename("file.xyz123")
        assert ext == ".txt"
        assert safe_name.endswith(".txt")

    def test_uuid_generation(self):
        """Test that UUID-based filename is generated by default."""
        safe_name1, _ = _sanitize_filename("test.pdf")
        safe_name2, _ = _sanitize_filename("other.pdf")
        # Should be different UUIDs
        assert safe_name1 != safe_name2
        # Should be 32 hex chars + .pdf = 36 chars total
        assert len(safe_name1) == 36
        assert safe_name1.endswith(".pdf")

    def test_non_uuid_mode(self):
        """Test sanitized original name when use_uuid=False."""
        safe_name, ext = _sanitize_filename("my document.pdf", use_uuid=False)
        assert safe_name == "my_document.pdf"

    def test_non_uuid_mode_spaces_to_underscores(self):
        """Test spaces converted to underscores in non-UUID mode."""
        safe_name, ext = _sanitize_filename("my file name.pdf", use_uuid=False)
        assert " " not in safe_name
        assert safe_name == "my_file_name.pdf"

    def test_very_long_filename(self):
        """Test long filenames are truncated."""
        long_name = "a" * 500 + ".pdf"
        safe_name, ext = _sanitize_filename(long_name)
        assert len(safe_name) <= 100 + 4  # stem max + ext

    def test_only_dots_becomes_file(self):
        """Test that name with only dots becomes 'file'."""
        safe_name, _ = _sanitize_filename("...", use_uuid=False)
        assert safe_name == "file.txt" or safe_name.startswith("file")


class TestMIMEValidation:
    """Tests for validate_mime_type function."""

    def test_valid_pdf(self):
        """Test PDF validation."""
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
            # Write proper PDF header that filetype can detect
            f.write(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n1 0 obj\nendobj\n")
            f.flush()
            temp_path = f.name

        try:
            valid, mime, error = validate_mime_type(temp_path, "test.pdf")
            assert valid, f"PDF should be valid, error: {error}"
            assert mime == "application/pdf"
        finally:
            os.unlink(temp_path)

    def test_valid_pdf_in_non_uuid_mode(self):
        """Test plain text validation using PDF extension."""
        # .pdf is supported
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
            f.write(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n1 0 obj\nendobj\n")
            f.flush()
            temp_path = f.name

        try:
            valid, mime, error = validate_mime_type(temp_path, "test.pdf")
            assert valid, f"PDF should be valid, error: {error}"
            assert mime == "application/pdf"
        finally:
            os.unlink(temp_path)

    def test_mime_extension_mismatch(self):
        """Test that MIME mismatch is detected."""
        # Create PDF content but name it .txt
        with tempfile.NamedTemporaryFile(suffix=".txt", delete=False) as f:
            f.write(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n1 0 obj\nendobj\n")
            f.flush()
            temp_path = f.name

        try:
            valid, mime, error = validate_mime_type(temp_path, "fake.txt")
            assert not valid, "Should reject PDF content with .txt extension"
            # Error could be about mismatch or unsupported extension
            assert error  # Non-empty error
        finally:
            os.unlink(temp_path)

    def test_empty_file_rejected(self):
        """Test that empty files are rejected."""
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
            f.flush()
            temp_path = f.name

        try:
            valid, mime, error = validate_mime_type(temp_path, "empty.pdf")
            assert not valid
            assert "empty" in error.lower()
        finally:
            os.unlink(temp_path)

    def test_unsupported_extension(self):
        """Test that unsupported extensions are rejected."""
        with tempfile.NamedTemporaryFile(suffix=".exe", delete=False) as f:
            f.write(b"MZ\x90\x00")  # EXE header
            f.flush()
            temp_path = f.name

        try:
            valid, mime, error = validate_mime_type(temp_path, "malware.exe")
            assert not valid
            assert "not supported" in error
        finally:
            os.unlink(temp_path)

    def test_nonexistent_file(self):
        """Test that nonexistent file is rejected."""
        valid, mime, error = validate_mime_type("/nonexistent/path.pdf", "test.pdf")
        assert not valid
        assert "does not exist" in error

    def test_size_limit_enforced(self):
        """Test that file size limit is enforced."""
        from backend.config_loader import settings
        max_size = int(settings.max_upload_bytes) if isinstance(settings.max_upload_bytes, str) else settings.max_upload_bytes

        # Create a file larger than the limit
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
            f.write(b"x" * (max_size + 1024))
            f.flush()
            temp_path = f.name

        try:
            valid, mime, error = validate_mime_type(temp_path, "large.pdf")
            assert not valid
            assert "exceeds" in error.lower()
        finally:
            os.unlink(temp_path)

    def test_docx_validation(self):
        """Test DOCX file validation."""
        # Create minimal DOCX (ZIP with correct structure)
        import zipfile
        with tempfile.NamedTemporaryFile(suffix=".docx", delete=False) as f:
            with zipfile.ZipFile(f, 'w') as zf:
                zf.writestr('[Content_Types].xml', '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>')
                zf.writestr('_rels/.rels', '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>')
                zf.writestr('word/document.xml', '<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>Test</w:t></w:r></w:p></w:body></w:document>')
            f.flush()
            temp_path = f.name

        try:
            valid, mime, error = validate_mime_type(temp_path, "test.docx")
            assert valid, f"DOCX should be valid, error: {error}"
            assert "wordprocessingml" in mime or "msword" in mime or "document" in mime
        finally:
            os.unlink(temp_path)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
